#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'viralligator_types'

module Viralligator
  class Client
    include ::Thrift::Client

    def publish(url, tags)
      send_publish(url, tags)
      recv_publish()
    end

    def send_publish(url, tags)
      send_message('publish', Publish_args, :url => url, :tags => tags)
    end

    def recv_publish()
      result = receive_message(Publish_result)
      return
    end

    def sharings(tags)
      send_sharings(tags)
      return recv_sharings()
    end

    def send_sharings(tags)
      send_message('sharings', Sharings_args, :tags => tags)
    end

    def recv_sharings()
      result = receive_message(Sharings_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'sharings failed: unknown result')
    end

    def shares_by_url(url)
      send_shares_by_url(url)
      return recv_shares_by_url()
    end

    def send_shares_by_url(url)
      send_message('shares_by_url', Shares_by_url_args, :url => url)
    end

    def recv_shares_by_url()
      result = receive_message(Shares_by_url_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'shares_by_url failed: unknown result')
    end

    def total_shares(url)
      send_total_shares(url)
      return recv_total_shares()
    end

    def send_total_shares(url)
      send_message('total_shares', Total_shares_args, :url => url)
    end

    def recv_total_shares()
      result = receive_message(Total_shares_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'total_shares failed: unknown result')
    end

    def fb_shares()
      send_fb_shares()
      return recv_fb_shares()
    end

    def send_fb_shares()
      send_message('fb_shares', Fb_shares_args)
    end

    def recv_fb_shares()
      result = receive_message(Fb_shares_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'fb_shares failed: unknown result')
    end

    def ok_shares()
      send_ok_shares()
      return recv_ok_shares()
    end

    def send_ok_shares()
      send_message('ok_shares', Ok_shares_args)
    end

    def recv_ok_shares()
      result = receive_message(Ok_shares_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'ok_shares failed: unknown result')
    end

    def vk_shares()
      send_vk_shares()
      return recv_vk_shares()
    end

    def send_vk_shares()
      send_message('vk_shares', Vk_shares_args)
    end

    def recv_vk_shares()
      result = receive_message(Vk_shares_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'vk_shares failed: unknown result')
    end

    def gplus_shares()
      send_gplus_shares()
      return recv_gplus_shares()
    end

    def send_gplus_shares()
      send_message('gplus_shares', Gplus_shares_args)
    end

    def recv_gplus_shares()
      result = receive_message(Gplus_shares_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'gplus_shares failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_publish(seqid, iprot, oprot)
      args = read_args(iprot, Publish_args)
      result = Publish_result.new()
      @handler.publish(args.url, args.tags)
      write_result(result, oprot, 'publish', seqid)
    end

    def process_sharings(seqid, iprot, oprot)
      args = read_args(iprot, Sharings_args)
      result = Sharings_result.new()
      result.success = @handler.sharings(args.tags)
      write_result(result, oprot, 'sharings', seqid)
    end

    def process_shares_by_url(seqid, iprot, oprot)
      args = read_args(iprot, Shares_by_url_args)
      result = Shares_by_url_result.new()
      result.success = @handler.shares_by_url(args.url)
      write_result(result, oprot, 'shares_by_url', seqid)
    end

    def process_total_shares(seqid, iprot, oprot)
      args = read_args(iprot, Total_shares_args)
      result = Total_shares_result.new()
      result.success = @handler.total_shares(args.url)
      write_result(result, oprot, 'total_shares', seqid)
    end

    def process_fb_shares(seqid, iprot, oprot)
      args = read_args(iprot, Fb_shares_args)
      result = Fb_shares_result.new()
      result.success = @handler.fb_shares()
      write_result(result, oprot, 'fb_shares', seqid)
    end

    def process_ok_shares(seqid, iprot, oprot)
      args = read_args(iprot, Ok_shares_args)
      result = Ok_shares_result.new()
      result.success = @handler.ok_shares()
      write_result(result, oprot, 'ok_shares', seqid)
    end

    def process_vk_shares(seqid, iprot, oprot)
      args = read_args(iprot, Vk_shares_args)
      result = Vk_shares_result.new()
      result.success = @handler.vk_shares()
      write_result(result, oprot, 'vk_shares', seqid)
    end

    def process_gplus_shares(seqid, iprot, oprot)
      args = read_args(iprot, Gplus_shares_args)
      result = Gplus_shares_result.new()
      result.success = @handler.gplus_shares()
      write_result(result, oprot, 'gplus_shares', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Publish_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    URL = 1
    TAGS = 2

    FIELDS = {
      URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
      TAGS => {:type => ::Thrift::Types::LIST, :name => 'tags', :element => {:type => ::Thrift::Types::STRING}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Publish_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Sharings_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    TAGS = 1

    FIELDS = {
      TAGS => {:type => ::Thrift::Types::LIST, :name => 'tags', :element => {:type => ::Thrift::Types::STRING}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Sharings_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::TotalShare}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Shares_by_url_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    URL = 1

    FIELDS = {
      URL => {:type => ::Thrift::Types::STRING, :name => 'url'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Shares_by_url_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::Sharing}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Total_shares_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    URL = 1

    FIELDS = {
      URL => {:type => ::Thrift::Types::STRING, :name => 'url'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Total_shares_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I64, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Fb_shares_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Fb_shares_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Sharing}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Ok_shares_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Ok_shares_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Sharing}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Vk_shares_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Vk_shares_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Sharing}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Gplus_shares_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Gplus_shares_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::LIST, :name => 'success', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Sharing}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

