%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(topic_service_thrift).
-behaviour(thrift_service).


-include("topic_service_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% topics_count(This)
function_info('topics_count', params_type) ->
  {struct, []}
;
function_info('topics_count', reply_type) ->
  i64;
function_info('topics_count', exceptions) ->
  {struct, []}
;
% getTopic(This, Url)
function_info('getTopic', params_type) ->
  {struct, [{1, string}]}
;
function_info('getTopic', reply_type) ->
  {struct, {'topic_types', 'Topic'}};
function_info('getTopic', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

