%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(viralligator_types).

-include("viralligator_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Share') ->
  {struct, [{1, string},
          {2, i64}]}
;

struct_info('Sharing') ->
  {struct, [{1, string},
          {2, {list, {struct, {'viralligator_types', 'Share'}}}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Share') ->
  {struct, [{1, undefined, string, 'social', undefined},
          {2, undefined, i64, 'count', undefined}]}
;

struct_info_ext('Sharing') ->
  {struct, [{1, optional, string, 'url', undefined},
          {2, optional, {list, {struct, {'viralligator_types', 'Share'}}}, 'shares', []}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

